name: .NET Core

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
    - name: Restore Dependencies
      run: dotnet restore Algorithms/Algorithms.sln
    - name: Build Solution
      run: dotnet build Algorithms/Algorithms.sln --configuration 'Release'
    - name: Run Tests
      run: dotnet test Algorithms/Algorithms.sln --configuration 'Release'
