name: .NET Core

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build solution
      run: dotnet build --configuration 'Release'
    - name: Run Tests (Algorithms)
      run: dotnet test AlgorithmsTests/AlgorithmsTests.csproj --configuration 'Release'
    - name: Run Tests (OmegaCore)
      run: dotnet test OmegaCoreTests/OmegaCoreTests.csproj --configuration 'Release'
